### ISSUE TITLE
when will the readme document be completed

### ISSUE THREAD

**Issue by SmallMunich** [yancie-yjr/StreamYOLO#3]
Hi, @GOATmessi7 @yancie-yjr great wokrs. Can you enrich the readme about datasets preparing、how to training & validation and so on. hope to finish it soon. thanks

**Comment by yancie-yjr** [comment]
Hi, We have provided all API, please click the corresponding extension box.
![image](https://user-images.githubusercontent.com/57621290/165878129-aaf179a3-c704-4c8f-bfd4-dd578944b76f.png)
